#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Mentor Graphics Questa Advanced Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sat Sep 23 17:25:52 CEST 2023
# SW Build 3526262 on Mon Apr 18 15:47:01 MDT 2022
#
# IP Build 3524634 on Mon Apr 18 20:55:01 MDT 2022
#
# usage: elaborate.sh
#
# ****************************************************************************
bin_path="/nfs/opt/eda/tools/siemens/questa-2022.2/questasim/bin"
set -Eeuo pipefail
source tb_crc_8_elaborate.do 2>&1 | tee elaborate.log

