######################################################################
#
# File name : tb_crc_8_compile.do
# Created on: Sat Sep 23 17:25:49 CEST 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
/nfs/opt/eda/tools/siemens/questa-2022.2/questasim/bin/vlib questa_lib/work
/nfs/opt/eda/tools/siemens/questa-2022.2/questasim/bin/vlib questa_lib/msim

/nfs/opt/eda/tools/siemens/questa-2022.2/questasim/bin/vlib questa_lib/msim/xil_defaultlib

/nfs/opt/eda/tools/siemens/questa-2022.2/questasim/bin/vmap xil_defaultlib questa_lib/msim/xil_defaultlib

/nfs/opt/eda/tools/siemens/questa-2022.2/questasim/bin/vcom -64 -2008 -work xil_defaultlib  \
"../../../../../../rtl/crc_8.vhd" \
"../../../../../../tb/tb_crc_8.vhd" \


