######################################################################
#
# File name : tb_crc_8_wave.do
# Created on: Sat Sep 23 17:25:57 CEST 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
