######################################################################
#
# File name : tb_crc_8_elaborate.do
# Created on: Sat Sep 23 17:25:52 CEST 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
/nfs/opt/eda/tools/siemens/questa-2022.2/questasim/bin/vopt -64 +acc=npr -suppress 10016 -L xil_defaultlib -L secureip -work xil_defaultlib xil_defaultlib.tb_crc_8 -o tb_crc_8_opt
