######################################################################
#
# File name : tb_crc_8_elaborate.do
# Created on: Wed Sep 27 20:16:23 CEST 2023
#
# Auto generated by Vivado for 'post-implementation' simulation
#
######################################################################
/nfs/opt/eda/tools/siemens/questa-2022.2/questasim/bin/vopt -64 +acc=npr -suppress 10016 -L xil_defaultlib -L simprims_ver -L secureip -work xil_defaultlib xil_defaultlib.tb_crc_8 xil_defaultlib.glbl -o tb_crc_8_opt
