######################################################################
#
# File name : tb_crc_8_simulate.do
# Created on: Wed Sep 27 20:16:29 CEST 2023
#
# Auto generated by Vivado for 'post-implementation' simulation
#
######################################################################
vsim +transport_int_delays +pulse_e/0 +pulse_int_e/0 +pulse_r/0 +pulse_int_r/0 -lib xil_defaultlib tb_crc_8_opt

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_crc_8_wave.do}

view wave
view structure
view signals

do {tb_crc_8.udo}

run 1000ns
