######################################################################
#
# File name : tb_crc_8_compile.do
# Created on: Wed Sep 27 20:16:19 CEST 2023
#
# Auto generated by Vivado for 'post-implementation' simulation
#
######################################################################
/nfs/opt/eda/tools/siemens/questa-2022.2/questasim/bin/vlib questa_lib/work
/nfs/opt/eda/tools/siemens/questa-2022.2/questasim/bin/vlib questa_lib/msim

/nfs/opt/eda/tools/siemens/questa-2022.2/questasim/bin/vlib questa_lib/msim/xil_defaultlib

/nfs/opt/eda/tools/siemens/questa-2022.2/questasim/bin/vmap xil_defaultlib questa_lib/msim/xil_defaultlib

/nfs/opt/eda/tools/siemens/questa-2022.2/questasim/bin/vlog -64 -incr -mfcu -work xil_defaultlib  \
"tb_crc_8_time_impl.v" \

/nfs/opt/eda/tools/siemens/questa-2022.2/questasim/bin/vcom -64 -2008 -work xil_defaultlib  \
"../../../../../../../tb/tb_crc_8.vhd" \


