######################################################################
#
# File name : tb_crc_8_wave.do
# Created on: Wed Sep 27 20:16:29 CEST 2023
#
# Auto generated by Vivado for 'post-implementation' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
